language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=1.4.5
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install -r test_app/requirements.txt
  - python setup.py -q install
script:
  - coverage run --source=confirmanager manage.py test
after_success:
  - coveralls